groups:
  - name: app_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(error_count[1m]) > 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 1 per second for 30 seconds."

      - alert: SlowResponseTime
        expr: histogram_quantile(0.9, rate(response_time_seconds_bucket[1m])) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Slow response time"
          description: "90th percentile response time is > 1 second."
