name: CI/CD Pipeline

permissions:
  contents: read
  security-events: write

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python, javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  deploy:
    name: Deploy to Environment
    needs: analyze
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev' || github.ref_name == 'staging' || github.ref_name == 'main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to environment
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "📦 Deploying from branch: $BRANCH_NAME"

          if [ "$BRANCH_NAME" = "dev" ]; then
            echo "🚀 Deploying to DEV server..."
            ssh -o StrictHostKeyChecking=no -i key.pem azureuser@20.195.40.50 \
              'cd /home/azureuser/Geeth-_AI_Desktop-_Assistant && git pull origin dev && sudo systemctl restart geeth-assistant.service'

          elif [ "$BRANCH_NAME" = "staging" ]; then
            echo "🚀 Deploying to STAGING server..."
            ssh -o StrictHostKeyChecking=no -i key.pem azureuser@20.195.40.50 \
              'cd /home/azureuser/Geeth-_AI_Desktop-_Assistant && git pull origin staging && sudo systemctl restart geeth-assistant.service'

          elif [ "$BRANCH_NAME" = "main" ]; then
            echo "🚀 Deploying to PRODUCTION server..."
            ssh -o StrictHostKeyChecking=no -i key.pem azureuser@20.195.40.50 \
              'cd /home/azureuser/Geeth-_AI_Desktop-_Assistant && git pull origin main && sudo systemctl restart geeth-assistant.service'

          else
            echo "❌ Unknown branch: $BRANCH_NAME"
            exit 1
          fi

      - name: DAST Scan Simulation
        run: |
          echo "Running DAST scan..."
          echo "<results><vuln>Low</vuln></results>" > results.xml
          if grep -q "High" results.xml; then
            echo "High vulnerabilities found!"
          exit 1
          fi
